---
title: "Relatório de Atendimento Médico Individual"
author: "Robson Wilson Silva Pessoa"
format: html
editor: visual
---

## Atividades 


## Running Code


```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
library(readxl)
library(dplyr)
library(magrittr)
library(tidyr)
library(lubridate)
# Fonte: 
# Data: 
# Time: 

# Leitura especificada - preservacao dados original
df <- read_excel("data/RelatorioSaudeProducao.xls",      
                 range = "A12:M39")

df2023 <- read_excel("data/RelatorioSaudeProducao2023.xls",      
                 range = "A14:C41")



df %<>% arrange(Estado)
df2023 %<>% arrange(Estado)


# Remocao de pontos de milhar dos caracters 
df %<>% mutate(across(where(is.character), ~ gsub('.','',.x,fixed = TRUE)))
df2023 %<>% mutate(across(where(is.character), ~ gsub('.','',.x,fixed = TRUE)))

# Conversao de character em numeric
df %<>% mutate(across(`DEZ/2022`:`JAN/2022`, ~ as.numeric(.x)))
df2023 %<>% mutate(across(`FEV/2023`:`JAN/2023`, ~ as.numeric(.x)))

# Siglas dos estados brasileiros 
ABREV <- c("AC","AL","AP","AM",
            "BA","CE","DF","ES",
            "GO","MA","MT","MS",
            "MG","PA","PB","PR",
            "PE","PI","RJ","RN",
            "RS","RO","RR","SC",
            "SP","SE","TO")

# Lista de Estados em ordem alfabetica
Estado <- levels(as.factor(df$Estado))


dfref <- as_tibble(data.frame(Estado,ABREV))




# unindo dois arquivos coletados separadamente
df <- inner_join(df2023,df,"Estado"="Estado")

df <- inner_join(df,dfref,"Estado"="Estado")


# gather
df %<>% gather(key='mes',value = 'atendimentos',-c(Estado,ABREV)) 



```


```{r, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
library(geobr)
library(ggplot2)
library(sf)


# read all states
states <- read_state(
  year=2020, 
  showProgress = FALSE
  )

# totalizacao por estado 
dfs <- df %>% 
          filter(mes %in% c("JAN/2023")) %>% 
          group_by(ABREV) %>% 
          summarise(total = atendimentos) # correcao de escala

 

states$abbrev_state <- tolower(states$abbrev_state)
dfs$ABREV <- tolower(dfs$ABREV)

# join the databases
states <- dplyr::left_join(states, dfs, by = c("abbrev_state" = "ABREV"))

# Remove plot axis
no_axis <- theme(axis.title=element_blank(),
                 axis.text=element_blank(),
                 axis.ticks=element_blank())

ggplot() +
  geom_sf(data=states, aes(fill=total), color= NA, size=.15) +
    labs(subtitle="Atendimento Individual realizado por Médico, 2022", size=8) +
    scale_fill_distiller(palette = "Blues", name=" ", limits = c(0,50)) +
  guides(fill=guide_legend(title="Milhões de atendimentos"))+
  scale_fill_distiller(direction = 1)+
    theme_minimal() +
    no_axis+
  labs(caption = "Fonte: Sistemas de Informação em Saúde para a Atenção Básica (SISAB)")
    
```
